name = "blog-gozamadrid"
type = "webpack"
account_id = "" # Deberás completar esto con tu ID de cuenta de Cloudflare
workers_dev = true
route = "blog.realestategozamadrid.com/*"
zone_id = "" # Deberás completar esto con el ID de zona de tu dominio en Cloudflare

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
workers_dev = false
route = "blog.realestategozamadrid.com/*"
zone_id = "" # Deberás completar esto con el ID de zona de tu dominio en Cloudflare 